language: python
python:
  - "3.6"

before_install:
  - pip install python-coveralls

install:
  - pip install -r requirements-dev.txt

script:
  - make test
  - make lint

after_success:
  - coveralls --data_file tests/.coverage
