language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - pip python-coveralls

install:
  - pip install -r requirements-dev.txt

script:
  - make test
  - make lint

after_success:
  - coveralls
